In [8]:
import pandas as pd
df = pd.read_csv("data/heetch.csv")
df.columns
p1 = Point(24.952242, 60.1696017)

In [6]:
from shapely.geometry import Point, Polygon

df["point"] = df.apply(lambda x: Point(x["Origin Latitude"],x["Origin Longitude"]), axis=1)

In [16]:

df["lol"] = df.apply(lambda x: Point(x["Origin Latitude"],x["Origin Longitude"]), axis=1)

In [21]:
df["lol"].apply(lambda x: p1.contains(x)

0         False
1         False
2         False
3         False
4         False
          ...
101038    False
101039    False
101040    False
101041    False
101042    False
Name: lol, Length: 101043, dtype: bool

In [26]:
df.loc[df["lol"].apply(lambda x: p1.contains(x) != True),"test"] = "TOP"

In [27]:
df

,Created At,Driver Id,Estimated Approach Duration,Estimated Price,Id,Origin Address,Origin Latitude,Origin Longitude,Payment Mode,State,User Id,pick_up_venue_type,lol,test
0,2019-10-20 18:55:00,1000007.0,180.0,11,0edc6f9d-08a6-4e08-96cb-028bb8face34,"10 Rue Emile Reynaud - 75019 Paris, France",48.901567,2.387198,cash,terminated,456033,NaN,POINT (48.901567 2.387198),TOP
1,2019-10-23 1:22:59,1000007.0,240.0,9,2e3e0993-ca27-41dd-941f-3ac41bb11197,"7 Avenue Arago, 94340 Joinville-le-Pont",48.825007,2.473905,cash,terminated,180992,NaN,POINT (48.825007 2.473905),TOP
2,2019-10-22 0:28:04,1000007.0,120.0,14,3e871a03-875c-4461-b256-e3d2d3dd8390,8 Rue de Berri - 75008 Paris,48.872184,2.304016,cash,terminated,430968,NaN,POINT (48.872184 2.304016),TOP
3,2019-10-23 0:26:15,1000007.0,360.0,6,4c4d8595-9160-4880-b8bd-b157a5ba2b43,38 Rue Saint-Dominique - 75007 Paris,48.860068,2.311160,cash,canceled_by_user,1070974,NaN,POINT (48.860068 2.31116),TOP
4,2019-10-22 0:13:19,1000007.0,240.0,10,6c903bfb-dcc9-4a37-8620-6aaf3a933fcc,29 Rue du Docteur Babinski - 93400 Saint-Ouen,48.901163,2.332574,cash,terminated,603407,NaN,POINT (48.901163 2.332574),TOP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101038,2019-10-19 18:20:48,NaN,NaN,31,ff1986bb-3a00-43e6-9c85-c9cade19a670,"Place Louis Armand, 75012 Paris",48.845007,2.373006,cash,booking_failed,1062957,Gare de Lyon,POINT (48.845007 2.373006),TOP
101039,2019-10-19 19:44:03,NaN,NaN,21,ff471107-0e2c-40e8-b9b7-7b1d38774a38,"Terminal Ouest, 94390 Paray-Vieille-Poste",48.729667,2.360141,cash,booking_failed,518867,Orly,POINT (48.729667 2.360141),TOP
101040,2019-10-23 19:11:42,NaN,NaN,28,ffa19eff-7077-407a-9f80-6ff35cd49e6f,"A√©roport Paris‚ÄìCharles de Gaulle, 93290 Tre...",49.002886,2.563522,cash,booking_failed,599570,Roissy,POINT (49.002886 2.563522),TOP
101041,2019-10-20 20:03:48,NaN,NaN,32,ffb08adc-efe2-4b01-ae17-fd3734ea73e3,"Terminal Ouest, 94390 Paray-Vieille-Poste",48.729667,2.360141,cash,booking_failed,805722,Orly,POINT (48.729667 2.360141),TOP
101042,2019-10-21 18:40:23,NaN,NaN,17,ffdd09c3-9e76-4b35-b42b-124bc580ad24,210 All√©e de Bercy - 75012 Paris-12E-Arrondis...,48.844389,2.372980,card,canceled_by_user,354431,Gare de Lyon,POINT (48.844389 2.37298),TOP